import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Provider from "./components/Provider";
import Header from "./components/Header";
import { Toaster } from "sonner";

const work_san = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog drcmind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`mx-4 lg:mx-60  ${work_san.className}`}>
        <Provider>
          <Header />

          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
